Repository flowervoca/flowerary, pull requests merged in 2025-04, with the labels that each got.

#1 🐛 layout.tsx 파일에 suppressHydrationWarning 속성 추가
  front/src/app/layout.tsx
Labels: [D-0] 긴급 수정사항 금일 바로 적용 요청

#2 ✨ GitHub Actions: simple-labeler 워크플로우 추가
  .github/workflows/simple-labeler.yml
Labels: D-3

#4 Feature/create d day labeler
  .github/workflows/d-day-labeler.yml
  .github/workflows/simple-labeler.yml
Labels: D-3

#6 Update d-day-labeler.yml
  .github/workflows/d-day-labeler.yml
Labels: D-3

#7 Update bottom-banners component to unify banner titles
  front/src/app/(main)/(components)/bottom-banners.tsx
Labels: D-1

#9 Feature/init
  front/README.md
  front/next.config.ts
  front/package.json
  front/pnpm-lock.yaml
  front/postcss.config.mjs
  front/src/app/(main)/globals.css
  front/src/app/(main)/layout.tsx
  front/src/app/globals.css
  front/src/app/layout.tsx
  front/src/assets/fonts/PretendardVariable.woff2
  front/tailwind.config.ts
  front/tsconfig.json
Labels: D-2
